#!/bin/bash -ex

# The chaining of find and grep was deemded necessary due to find's lack of a
# proper regex implementation. Also note that on linux find does not support
# -E like on BSDs.

find . -print0 | xargs -r -0 -P "$(nproc)" -i bash -c '
set -x
echo {} | grep -E $2 > /dev/null 
MATCH=$?

if [ $MATCH -eq 0 ]; then
  cd $(dirname "$1")
  "$3" "$(basename "$1")"
elif [ $MATCH -ne 1 ]; then
  exit 1
fi
' - '{}' "$1" "$2"
