# SPDX-FileCopyrightText: 2022 Luca Tagliavini <luca.tagliavini5@studio.unibo.it>
# SPDX-FileCopyrightText: 2023 Stefano Volpe <stefano.volpe@student.uva.nl>
#
# SPDX-License-Identifier: AGPL-3.0-only

name: build

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest on main
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Remove / form github.ref_name
        run: |
          a=${{ github.ref_name }}
          echo "branch_name=${a//\//-}" >> $GITHUB_ENV

      - name: Build and push with ref name
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.branch_name }}
